d3.select('#header')
  .append('svg')
    .attr('width', 500)
    .attr('height', 500)
    .style('background', '#ffffff')
  .append('text')
    .attr('x', 75)
    .attr('y', 250)
    .style({'fill':'blue','font-size':'100'})
    .text('About.Me');
