d3.select('#header')
  .append('svg')
    .attr('width', 350)
    .attr('height', 250)
    .style('background', 'MediumBlue')
  .append('text')
    .attr('x', 10)
    .attr('y', 90)
    .style({'fill':'White','font-size':'60'})
    .text('About.Me');
